help:
    
 manual:
   general: http://handbuch.fairgate.ch/
   document: http://handbuch.fairgate.ch/category/dokumente
   contact: http://handbuch.fairgate.ch/category/kontaktverwaltung
   sponsor: http://handbuch.fairgate.ch/category/sponsorenverwaltung
   communication: http://handbuch.fairgate.ch/category/kommunikation
   
 video:
   channel: https://www.youtube.com/channel/UCQghijR5j4tPJl7Os8nvYVA
   
   playlists:
     quicktips: http://handbuch.fairgate.ch/778
     videotutorials: http://handbuch.fairgate.ch/778
     
   promovideos:
     documents: https://www.youtube.com/watch?v=wge9N9jlZ_U
     sponsor: https://www.youtube.com/watch?v=wge9N9jlZ_U
     newsletter: https://www.youtube.com/watch?v=wge9N9jlZ_U
     
 facebook: https://facebook.com/Fairgate-AG-139151186126484/ 
 
 google+: https://plus.google.com/u/0/103879614238188552690/posts
 
 twitter: https://twitter.com/fairgateag
 support: http://support.fairgate.ch/osticket/
 
channel-playlist: https://www.googleapis.com/youtube/v3/playlists?part=snippet&channelId=UCQghijR5j4tPJl7Os8nvYVA&key=AIzaSyCqoymXav-_Go1zYa9UOlPf5_UsC58Jmi0