help_quickstart:
    path:     /quickstart
    defaults: { _controller: CommonHelpBundle:Default:index }
    
help_quickstart_resource:
    path:     /quickstart/resource
    defaults: { _controller: CommonHelpBundle:Default:resource }
    
help_dontshow_checkbox:
    path:     /quickstart/dontshowPopup
    defaults: { _controller: CommonHelpBundle:Default:quickWindowVisibility }  
    
help_content_details:
    path:     /quickstart/contentdetails
    defaults: { _controller: CommonHelpBundle:Default:getHelpContentDetails } 
    
help_playlist_videos:
    path:     /playlist/videolists
    defaults: { _controller: CommonHelpBundle:Default:playlistVideo }  

