parameters:
#    internal_message.example.class: Internal\MessageBundle\Example

services:
#    internal_message.example:
#        class: %internal_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
