Admin\UtilityBundle\Entity\FgClubAddress:
    type: entity
    table: fg_club_address
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        company:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        street:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        pobox:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        city:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        zipcode:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        state:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        country:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        language:
            type: string
            nullable: true
            length: 2
            options:
                fixed: true
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        co:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
