Admin\UtilityBundle\Entity\FgClubClass:
    type: entity
    table: fg_club_class
    indexes:
        fk_fg_club_class_fg_club_classification1:
            columns:
                - classification_id
        fk_fg_club_class_fg_club1:
            columns:
                - federation_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
        sortOrder:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: sort_order
    manyToOne:
        classification:
            targetEntity: FgClubClassification
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                classification_id:
                    referencedColumnName: id
            orphanRemoval: false
        federation:
            targetEntity: FgClub
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                federation_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
