Admin\UtilityBundle\Entity\FgClubClassification:
    repositoryClass: Admin\UtilityBundle\Repository\FgClubClassificationRepository
    type: entity
    table: fg_club_classification
    indexes:
        index_category:
            columns:
                - is_active
        fk_fg_club_classification_fg_club1:
            columns:
                - federation_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        sublevelAssign:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                default: 'not visible'
            column: sublevel_assign
        classAssign:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                default: multiple
            column: class_assign
        isActive:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: is_active
        sortOrder:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: sort_order
    manyToOne:
        federation:
            targetEntity: FgClub
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                federation_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
