parameters:
#    internal_user.example.class: Internal\UserBundle\Example

services:
#    internal_user.example:
#        class: %internal_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
