parameters:
#    internal_calendar.example.class: Internal\CalendarBundle\Example

services:
#    internal_calendar.example:
#        class: %internal_calendar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
