<?php 
/**
 * FgCmsPageContentElementLogRepository.
 *
 * @package 	CommonUtilityBundle
 * @subpackage 	Repository
 * @author     	pitsolutions.ch
 * @version    	Fairgate V4
 *
 */
namespace Common\UtilityBundle\Repository\cms;

use Doctrine\ORM\EntityRepository;
use Common\UtilityBundle\Util\FgSettings;

/**
 * FgCmsPageContentElementLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FgCmsPageContentElementLogRepository extends EntityRepository
{

    /**
     * Function to get the log entries of a particular element
     * 
     * @param int $elementId element id
     * @param int $clubId club Id
     * 
     * @return array $dataResult
     */
    public function getLogData($elementId, $clubId)
    {
        $clubDecidedDql = $this->getClubNameOfDecidedBy();
        $datetimeFormat = FgSettings::getMysqlDateTimeFormat();
        $doctrineConfig = $this->getEntityManager()->getConfiguration();
        $doctrineConfig->addCustomStringFunction('DATE_FORMAT', 'Common\UtilityBundle\Extensions\DateFormat');
        $doctrineConfig->addCustomStringFunction('contactNameNoSort', 'Common\UtilityBundle\Extensions\FetchContactNameNoSort');
        $doctrineConfig->addCustomStringFunction('checkActiveContact', 'Common\UtilityBundle\Extensions\CheckActiveContact');

        $log = $this->createQueryBuilder('l')
            ->select("l.type , l.valueAfter, IDENTITY(l.changedBy) as changedBy, l.valueBefore, contactNameNoSort(l.changedBy 0) as contact, CheckActiveContact(l.changedBy, :clubId) as activeContactId, (DATE_FORMAT(l.date, '$datetimeFormat')) as date, l.action as status, fcc.isStealthMode as isStealth")
            ->addSelect('(' . $clubDecidedDql->getDQL() . ') AS clubChangedBy ')
            ->leftJoin('CommonUtilityBundle:FgCmsPageContentElement', 'e', 'WITH', 'e.id = l.element')
            ->leftJoin('CommonUtilityBundle:FgCmContact', 'fcc', 'WITH', 'fcc.id = l.changedBy')
            ->where('l.element=:elementId')
            ->orderBy('l.id', 'DESC')
            ->setParameters(array('elementId' => $elementId, 'clubId' => $clubId));

        return $log->getQuery()->getArrayResult();
    }

    /**
     * Function to get the  club.
     *
     * @return Integer
     */
    private function getClubNameOfDecidedBy()
    {
        $moduleQuery = $this->getEntityManager()->createQueryBuilder();
        $moduleQuery->select('fc1.title')
            ->from('CommonUtilityBundle:FgCmContact', 'ct1')
            ->innerJoin('CommonUtilityBundle:FgClub', 'fc1', 'WITH', 'ct1.mainClub = fc1.id')
            ->where('ct1.id = l.changedBy');

        return $moduleQuery;
    }
}
