<?php

/**
 * FgCmsPageContentTextElementHistoryI18nRepository.
 *
 * @package 	CommonUtilityBundle
 * @subpackage 	Repository
 * @author     	pitsolutions.ch
 * @version    	Fairgate V4
 *
 */
namespace Common\UtilityBundle\Repository\Cms;

use Doctrine\ORM\EntityRepository;

/**
 * FgCmsPageContentTextElementHistoryI18nRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FgCmsPageContentTextElementHistoryI18nRepository extends EntityRepository
{

    /**
     * Function to create the text entry and text18n
     * This function will also update the text-version
     *
     * @param array $textArray     The array with the details to be saved
     * @param int   $textVersionId The current text version
     * @param array $clubLanguages The array of languages available to the user
     * @param int   $textElementId text element id
     * @param string$defaultClubLang default club language
     */
    public function insertTextElementHistoryi18n($textArray, $textVersionId, $clubLanguages, $textElementId, $defaultClubLang)
    {
        $prevHistory = $prevHist = array();
        if (isset($textArray[$defaultClubLang]['text'])) {
            $prevVersionObj = $this->_em->getRepository('CommonUtilityBundle:FgCmsPageContentTextElement')->find($textElementId);
            if ($prevVersionObj->getVersion() != '') {
                $prevVersionId = $prevVersionObj->getVersion()->getId();
                $query = "SELECT lang,text_lang FROM fg_cms_page_content_text_element_history_i18n WHERE id = '" . $prevVersionId . "'";
                $conn = $this->getEntityManager()->getConnection();
                $prevHistory = $conn->executeQuery($query);
                foreach ($prevHistory as $value) {
                    $prevHist[$value['lang']]['text'] = $value['text_lang'];
                }
            }
            $finalResult = array_merge($prevHist, $textArray);
        } else {
            $finalResult = $textArray;
        }

        foreach ($clubLanguages as $language) {
            if (isset($finalResult[$language]['text'])) {
                $textLang = str_replace('<script', '<scri&nbsp;pt', $finalResult[$language]['text']);

                $query = "INSERT INTO fg_cms_page_content_text_element_history_i18n (id,lang,text_lang)  VALUES ($textVersionId,'$language','$textLang') "
                    . "ON DUPLICATE KEY UPDATE lang = VALUES(lang),text_lang = VALUES(text_lang)";

                $conn = $this->getEntityManager()->getConnection();
                $conn->executeQuery($query);
            }
        }

        return;
    }
}
