<?php 
/**
 * FgCmsPageI18nRepository.
 *
 * @package 	CommonUtilityBundle
 * @subpackage 	Repository
 * @author     	pitsolutions.ch
 * @version    	Fairgate V4
 *
 */
namespace Common\UtilityBundle\Repository\Cms;

use Doctrine\ORM\EntityRepository;

/**
 * FgCmsPageI18nRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FgCmsPageI18nRepository extends EntityRepository
{ /**
 * This function is used to update page title entry to i18n table. 
 * 
 * @param type $id       Page Id
 * @param type $lang     Lang
 * @param type $title    Title
 */

    public function updatePageI18n($id, $lang, $title)
    {
        $qb = $this->createQueryBuilder();
        $que = $qb->update('CommonUtilityBundle:FgCmsPageI18n', 'pi18n')
            ->set('pi18n.titleLang', ":title")
            ->where('pi18n.lang=:lang')
            ->andWhere('pi18n.id =:pageId')
            ->setParameter('pageId', $id)
            ->setParameter('lang', $lang)
            ->setParameter('title', $title)
            ->getQuery();
        $que->execute();

        return true;
    }
}
