parameters:
#    internal_team.example.class: Internal\TeamBundle\Example

services:
#    internal_team.example:
#        class: %internal_team.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
