parameters:
#    clubadmin_documents.example.class: Clubadmin\DocumentsBundle\Example

services:
#    clubadmin_documents.example:
#        class: %clubadmin_documents.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
