parameters:
#    clubadmin_sponsor.example.class: Clubadmin\SponsorBundle\Example

services:
#    clubadmin_sponsor.example:
#        class: %clubadmin_sponsor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
