upload_path_change:
    path:     /{filename}
    defaults: { _controller: InternalGeneralBundle:Dashboard:changeFilePath } 
    
upload_path_change_article:
    path:     /article_images/{filename}
    defaults: { _controller: InternalGeneralBundle:Dashboard:changeFilePath }
    
upload_path_article_original:
    path:     /article_images/original/{filename}
    defaults: { _controller: InternalGeneralBundle:Dashboard:changeFilePath }
    
upload_path_change_resize:
    path:     /article_images/171X114/{filename}
    defaults: { _controller: InternalGeneralBundle:Dashboard:changeFilePath }       