parameters:
#    clubadmin_general.example.class: Clubadmin\GeneralBundle\Example

services:
#    clubadmin_general.example:
#        class: %clubadmin_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
