# Assetic Configuration
assetic:
    assets:
        jqueryAndUi:
            inputs:
                - 'assets/global/plugins/jquery-1.11.0.min.js'
                - 'assets/global/plugins/jquery-migrate-1.2.1.min.js'
                - 'assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js'
                - 'assets/global/plugins/bootstrap/js/bootstrap.min.js'
                - 'assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js'
                - 'assets/global/plugins/jquery.blockui.min.js'
                - 'assets/global/plugins/jquery.cokie.min.js'
                - 'assets/global/plugins/uniform/jquery.uniform.min.js'
        metronicAndLayout:
            inputs:
                - 'assets/global/scripts/metronic.js'
                - 'assets/admin/layout/scripts/layout.js'
        jqueryElements1:
            inputs:
                - 'assets/global/plugins/jquery-multi-select/js/jquery.multi-select.js'
                - 'assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js'
                - 'assets/global/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.min.js'
                - 'assets/global/plugins/jquery-validation/js/jquery.validate.min.js'
                - 'assets/global/plugins/jquery-validation/js/additional-methods.min.js'
                - 'assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'
                - 'assets/global/plugins/bootstrap-datepicker/js/locales/bootstrap-datepicker.de.js'
                - 'assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js'
                - 'assets/global/plugins/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.de.js'
                - 'assets/global/plugins/typeahead/handlebars.min.js'
                - 'assets/global/plugins/typeahead/typeahead.bundle.js'
                - 'assets/global/plugins/jquery-tags-input/jquery.tagsinput.min.js'
                - 'assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js'
                - 'assets/global/plugins/data-tables/jquery.dataTables_10.js'
                - 'assets/global/plugins/data-tables/dataTables.fixedColumns.min_3.0.js'
                - 'assets/global/plugins/data-tables/DT_bootstrap.js'
                - 'assets/global/plugins/bootstrap-select/bootstrap-select.min.js'
                - 'assets/global/plugins/select2/select2.js'
                - 'fgassets/global/js/bootstrap-dropdown-on-hover.js'
                - 'fgassets/global/js/datetime-moment.js'
                - 'fgassets/global/js/accounting.js'

        jqueryElements2:
            inputs:
                - 'assets/global/plugins/jquery-multi-select/js/jquery.multi-select.js'
                - 'assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js'
                - 'assets/global/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.min.js'
                - 'assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'
                - 'assets/global/plugins/bootstrap-datepicker/js/locales/bootstrap-datepicker.de.js'
                - 'assets/global/plugins/jquery-tags-input/jquery.tagsinput.min.js'
                - 'assets/global/plugins/data-tables/jquery.dataTables_10.js'
                - 'assets/global/plugins/data-tables/dataTables.fixedColumns.min_3.0.js'
                - 'assets/global/plugins/data-tables/DT_bootstrap.js'
                - 'assets/global/plugins/bootstrap-select/bootstrap-select.min.js'
                - 'assets/global/plugins/select2/select2.js'
                - 'fgassets/global/js/bootstrap-dropdown-on-hover.js'
                - 'fgassets/global/js/datetime-moment.js'
                - 'fgassets/global/js/accounting.js'
#        fairgateScripts1:
#            inputs:
#                - 'fgcustom/js/dirtyform/jquery.are-you-sure.js'
#                - 'fgcustom/js/jquery.form.min.js'
#                - 'fgcustom/js/underscore-min.js'
#        fairgateScripts2:
#            inputs:
#                - 'fgcustom/js/custom-form-validation.js'
#                - 'fgcustom/js/autosize/jquery.autosize.js'
#                - 'fgcustom/js/jquery-inputmask/jquery.inputmask.bundle.min.js'
#                - 'fgcustom/js/fg_contact_list.js'
#                - 'assets/admin/pages/scripts/components-dropdowns.js'
#                - 'fgcustom/js/common.js'
#                - 'fgcustom/js/count-update.js'
        mandatoryCss:
            inputs:
                - 'assets/global/plugins/font-awesome/css/font-awesome.min.css'
                - 'assets/global/plugins/bootstrap/css/bootstrap.min.css'
                - 'assets/global/plugins/uniform/css/uniform.default.css'
                - 'assets/global/plugins/jquery-tags-input/jquery.tagsinput.css'
                - 'assets/global/plugins/bootstrap-markdown/css/bootstrap-markdown.min.css'
                - 'assets/global/plugins/jquery-multi-select/css/multi-select.css'
                - 'assets/global/plugins/select2/select2.css'
                - 'assets/global/plugins/bootstrap-switch/css/bootstrap-switch.css'
                - 'assets/global/plugins/bootstrap-datepicker/css/datepicker.css'
                - 'assets/global/plugins/bootstrap-datetimepicker/css/datetimepicker.css'
                - 'assets/global/plugins/bootstrap-toastr/toastr.min.css'
        themeCss:
            inputs:
                - 'assets/global/css/components.css'
                - 'assets/global/css/plugins.css'
                - 'assets/admin/layout/css/layout.css'
                - 'assets/admin/layout/css/themes/default.css'
                - 'assets/global/plugins/typeahead/typeahead.css'
                - 'assets/global/plugins/data-tables/DT_bootstrap.css'
                - 'assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css'
                - 'assets/global/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css'
                - 'assets/global/plugins/bootstrap-select/bootstrap-select.min.css'
                - 'fgassets/global/css/animate.min.css'
        fairgateCss:
            inputs:
                - 'fgcustom/css/bootstrap-toggle-switch.css'
                - 'fgcustom/tokenfield/css/bootstrap-tokenfield.css'
    debug:          "%kernel.debug%"
    read_from:      "%kernel.root_dir%/../../web"
    write_to:       "%kernel.root_dir%/../../web/minified"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ["%kernel.root_dir%/../../web"]
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
