parameters:
    default_doc_club_table_settings: 
        '1':
            id: SIZE
            type: FO
            club_id: '1'
            name: CL_FO_SIZE
        '2':
            id: UPLOADED
            type: DO
            club_id: '1'
            name: CL_DO_UPLOADED
        '3':
            id: UPLOADED_BY
            type: UO
            club_id: '1'
            name: CL_UO_UPLOADED_BY
        '4':
            id: VISIBLE_TO
            type: FO
            club_id: '1'
            name: CL_FO_VISIBLE_TO

            
    default_doc_team_table_settings:
        0:
            id:  'SIZE'
            type: 'FO'
            club_id: '1'
            name: 'T_FO_SIZE'
        1:
            id:  'UPLOADED'
            type: 'DO'
            club_id: '1'
            name: 'T_DO_UPLOADED'
        2:
            id:  'UPLOADED_BY'
            type: 'UO'
            club_id: '1'
            name: 'T_UO_UPLOADED_BY'
        3:
            id:  'DEPOSITED_WITH'
            type: 'FO'
            club_id: '1'
            name: 'T_FO_DEPOSITED_WITH' 
        4:
            id:  'VISIBLE_TO'
            type: 'FO'
            club_id: '1'
            name: 'T_FO_VISIBLE_TO'
        5:
            id:  'ISPUBLIC'
            type: 'FO'
            club_id: '1'
            name: 'T_FO_ISPUBLIC' 
    default_doc_workgroup_table_settings:
        0:
            id:  'SIZE'
            type: 'FO'
            club_id: '1'
            name: 'WG_FO_SIZE'
        1:
            id:  'UPLOADED'
            type: 'DO'
            club_id: '1'
            name: 'WG_DO_UPLOADED'
        2:
            id:  'UPLOADED_BY'
            type: 'UO'
            club_id: '1'
            name: 'WG_UO_UPLOADED_BY'
        3:
            id:  'DEPOSITED_WITH'
            type: 'FO'
            club_id: '1'
            name: 'WG_FO_DEPOSITED_WITH' 
        4:
            id:  'VISIBLE_TO'
            type: 'FO'
            club_id: '1'
            name: 'WG_FO_VISIBLE_TO'
        5:
            id:  'ISPUBLIC'
            type: 'FO'
            club_id: '1'
            name: 'WG_FO_ISPUBLIC'
    default_doc_contact_table_settings:
        0:
            id:  'SIZE'
            type: 'FO'
            club_id: '1'
            name: 'CO_FO_SIZE'
        1:
            id:  'UPLOADED'
            type: 'DO'
            club_id: '1'
            name: 'CO_DO_UPLOADED'
        2:
            id:  'UPLOADED_BY'
            type: 'UO'
            club_id: '1'
            name: 'CO_UO_UPLOADED_BY'
        3:
            id:  'VISIBLE_TO'
            type: 'FO'
            club_id: '1'
            name: 'CO_FO_VISIBLE_TO'
        4:
            id:  'ISPUBLIC'
            type: 'FO'
            club_id: '1'
            name: 'CO_FO_ISPUBLIC' 
        
      
 