_main:
    resource: routing.yml
    
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /{url_identifier}/backend/public/_wdt/

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /{url_identifier}/backend/public/_profiler/