parameters:
    themeFiles:
    #   themesfiles used in layout
        themeLayoutFiles: 
            theme1: 
                headerFile: '::website/header.html.twig'
                sidebarFile: website/sidebar.html.twig
                contentFile: website/content.html.twig
                footerFile: '::website/footer.html.twig'
                topnavFile: '::website/templateTopNavMenu.html.twig'
                pageTitleBarFile: '::website/templatePagetitlebar.html.twig'            
                headerLogosFile: '::website/templateHeaderLogos.html.twig'
                headerNavMenuFile: '::website/templateHeaderNavMenu.html.twig'
                backgroundFile: '::website/templateBackground.html.twig'
                themeScripts: '::website/themeScripts.html.twig'
            theme2:
                headerFile: '::website/theme_2/header.html.twig'
                sidebarFile: '::website/sidebar.html.twig'
                contentFile: '::website/content.html.twig'
                footerFile: '::website/theme_2/footer.html.twig'
                topnavFile: '::website/templateTopNavMenu.html.twig'
                pageTitleBarFile: '::website/theme_2/templatePagetitlebar.html.twig'
                headerLogosFile: '::website/theme_2/templateHeaderLogos.html.twig'
                headerNavMenuFile: '::website/templateHeaderNavMenu.html.twig'
                backgroundFile: '::website/templateBackground.html.twig'
                themeScripts: '::website/theme_2/themeScripts.html.twig'

    #   files that has changes in each theme
        themeChangedFiles:
            theme1:
                colorSchemeCssTemplate: 'WebsiteCMSBundle:CssTemplates:colorscheme.css.twig'
                themeConfCssTemplate: 'WebsiteCMSBundle:CssTemplates:themeConfiguration.css.twig'   
                contactApplicationForm: 'WebsiteCMSBundle:Website:contactApplicationFormUnderscore.html.twig'
                articleDetailPage: 'WebsiteCMSBundle:Article:websiteArticleDetails.html.twig' 
                gallerySpecialPage: 'WebsiteCMSBundle:Gallery:displayGallerySpecialPage.html.twig' 
                articleElementTemplate: 'WebsiteCMSBundle:Website:articleElementDisplayTemplate.html.twig' 
                articleSpecialPageTemplate: 'WebsiteCMSBundle:Article:templateArticleList.html.twig'
                formSubmitButtonTemplate: 'WebsiteCMSBundle:Website:templateFormFieldSubmit.html.twig'
                formCaptchaTemplate: 'WebsiteCMSBundle:Website:templateFormCaptcha.html.twig'
                formElementTemplate: 'WebsiteCMSBundle:Website:templateFormField.html.twig'
            theme2:
                colorSchemeCssTemplate: 'WebsiteCMSBundle:CssTemplates:Theme2\colorscheme.css.twig'
                themeConfCssTemplate: 'WebsiteCMSBundle:CssTemplates:Theme2\themeConfiguration.css.twig'             
                contactApplicationForm: 'WebsiteCMSBundle:Website:Theme2\contactApplicationFormUnderscore.html.twig'
                articleDetailPage: 'WebsiteCMSBundle:Article:Theme2\websiteArticleDetails.html.twig'
                gallerySpecialPage: 'WebsiteCMSBundle:Gallery:Theme2\displayGallerySpecialPage.html.twig' 
                articleElementTemplate: 'WebsiteCMSBundle:Article:Theme2\articleDisplayTemplate.html.twig' 
                articleSpecialPageTemplate: 'WebsiteCMSBundle:Article:Theme2\templateArticleList.html.twig'
                formSubmitButtonTemplate: 'WebsiteCMSBundle:Website:Theme2\templateFormFieldSubmit.html.twig' 
                formCaptchaTemplate: 'WebsiteCMSBundle:Website:Theme2\templateFormCaptcha.html.twig'
                formElementTemplate: 'WebsiteCMSBundle:Website:Theme2\templateFormField.html.twig'


