#!/bin/bash
#CRON JOBS FOR REMOVING OLD DOMAIN VERIFICATION FILES

cd /var/www/html/fairgate_fedv2_qa/fairgate4
php bin/console website:cleardomainfile --env=prod >> /var/www/html/fairgate_fedv2_qa/fairgate4/cronjob.log
date >> /var/www/html/fairgate_fedv2_qa/fairgate4/cronjob.log