#!/bin/bash
#CRON JOBS RUNNING EVERY 12 hours

#EVERY 15 MINUTES CRON
cd /var/www/html/fairgate_fedv2_qa/fairgate4
php bin/console stuckedmailalert:send --env=prod >> /var/www/html/fairgate_fedv2_qa/cronjob.log
date >> /var/www/html/fairgate_fedv2_qa/cronjob.log
