#!/bin/bash
#CRON JOBS RUNNING EVERY 15 MINUTES 

#EVERY 15 MINUTES CRON
cd /var/www/html/fairgate_fedv2_hotfix/fairgate4
php bin/console newsletter:send_from_spool --cron-instance=2 --message-limit=200 --time-limit=280 --env=prod >> /var/www/html/fairgate_fedv2_hotfix/cronjob.log
date >> /var/www/html/fairgate_fedv2_hotfix/cronjob.log
