#!/bin/bash
#CRON JOBS RUNNING EVERY 15 MINUTES

#EVERY 15 MINUTES CRON
cd /var/www/html/fairgate_development_s3/fairgate4
php bin/console notificationmail:send >> /var/www/html/fairgate_development_s3/cronjob.log
date >> /var/www/html/fairgate_development_s3/cronjob.log
