#!/bin/bash
#CRON JOBS RUNNING EVERY 5 MINUTES 

#EVERY 5 MINUTES CRON
cd /var/www/html/fairgate_development_s3/fairgate4
php bin/console newsletter:insert_to_spool --time-limit=280 --env=prod >> /var/www/html/fairgate_development_s3/cronjob.log
date >> /var/www/html/fairgate_development_s3/cronjob.log
