#!/bin/bash
#CRON JOBS RUNNING EVERY 15 MINUTES 

#EVERY 15 MINUTES CRON
cd /var/www/html/fairgate_development_s3/fairgate4
php bin/console newsletter:send_from_spool --cron-instance=4 --message-limit=200 --time-limit=280 --env=prod >> /var/www/html/fairgate_development_s3/cronjob.log
date >> /var/www/html/fairgate_development_s3/cronjob.log
