#!/bin/bash
#CRON JOBS FOR SAVING VIRUS NOTIFICATION LOG TO SPOOL

cd /var/www/html/fairgate_fedv2_qa/fairgate4
php bin/console viruslog:send_notification --env=prod >> /var/www/html/fairgate_fedv2_qa/fairgate4/cronjob.log
date >> /var/www/html/fairgate_fedv2_qa/fairgate4/cronjob.log
