services:
    article.create:
        class: Internal\ArticleBundle\Util\ArticleCreate
        arguments: ['@service_container']
    article.data:
        class: Internal\ArticleBundle\Util\ArticleData
        arguments: ['@service_container']
