parameters:
#    internal_general.example.class: Internal\GeneralBundle\Example

services:
#    internal_general.example:
#        class: %internal_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
