<?php

namespace Common\UtilityBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Common\UtilityBundle\Entity\FgCmAttributeI18n;

/**
 * FgCmAttributeI18nRepository Repository.
 *
 * This class was generated by the Doctrine ORM to manage FgCmAttributeI18n table functions
 */
class FgCmAttributeI18nRepository extends EntityRepository {
    
    /**
     * Method to get title of Correspondence Language in club's system language
     * 
     * @param string $systemFieldCorressLang Fieldname of Correspondence Language (515)
     * @param string $clubSystemLang         club's systm language
     * 
     * @return string
     */
    public function getCorrespondenceLangTitle($systemFieldCorressLang, $clubSystemLang) {
        
        $qb = $this->createQueryBuilder('A')
                ->select('A.fieldnameLang')               
                ->where('A.id=:systemFieldCorressLang AND A.lang = :clubSystemLang')
                ->setParameters(array('systemFieldCorressLang' => $systemFieldCorressLang,'clubSystemLang' => $clubSystemLang));
        $result = $qb->getQuery()->getResult();

        return $result[0]['fieldnameLang'];
    }

   

}
