<?php

Namespace Common\UtilityBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Common\UtilityBundle\Util\FgUtility;

/**
 * SfGuardUserClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SfGuardUserClubRepository extends EntityRepository
{
    /**
     * Function to get the club details
     *
     * @param int $loggedUserId Logged user id
     * @param int $clubId       Club id
     *
     * @return String Group name
     */
    public function getClubDetails($loggedUserId, $clubId)
    {
        $clubUser = $this->createQueryBuilder('cu')
                ->select('c.id')
                ->leftJoin('cu.user', 'u')
                ->leftJoin('cu.club', 'c')
                ->where('u.id=:loggedUserId')
                ->andWhere('c.id=:clubId')
                ->setParameter('loggedUserId', $loggedUserId)
                ->setParameter('clubId', $clubId);

        $clubUser = $clubUser->getQuery()->getResult();

        return $clubUser[0];
    }
}
