<?php

namespace Admin\UtilityBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Clubadmin\Util\Contactlist;
use Common\UtilityBundle\Util\FgUtility;
use Common\UtilityBundle\Util\FgSettings;
use Symfony\Component\Process\Process;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Common\UtilityBundle\Util\FgFedMemberships;
use Common\UtilityBundle\Util\FgLogHandler;

/**
 * FgCmContact Repository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FgCmContactRepository extends EntityRepository
{

    
}
