<?php

namespace Admin\UtilityBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Common\UtilityBundle\Entity\FgClubLanguageSettings;

/**
 * FgClubLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FgSubsubcategorisationRepository extends EntityRepository {

    /**
     * Function to update club language settings table when add/update language
     *
     * @param object  $catId       category id
     */
    
     public function getCategories($catId){
         
          $qb = $this->createQueryBuilder("ssc")
                   ->select('ssc.id AS subSubCatId, ssc.subsubcategoryName AS subSubCategory, sc.id AS subCatId, sc.subsubcategoryName AS subCategory')
                   ->leftJoin('AdminUtilityBundle:FgSubcategorisation', 'sc', 'WITH', 'sc.id = ssc.fgSubcategorisation')
                   ->leftJoin('AdminUtilityBundle:FgCategorisation', 'c', 'WITH', 'c.id = sc.fgCategorisation')
                   ->where('c.id=:catId')
                   ->orderBy('ssc.subsubcategoryName', 'ASC')
                   ->setParameter('catId', $catId);
         
          $result = $qb->getQuery()->getResult();  
         
          return $result;
     }
    
}