
terminology_manipulate:
    path: /settings/terminologymanipulate
    defaults: { _controller: TerminologyBundle:Terminology:index , level1: terminologymanipulate}
    
terminology_save:
    path: /settings/update
    defaults: { _controller: TerminologyBundle:Terminology:update , level1: terminologymanipulate}
    
