parameters:
#    internal_profile.example.class: Internal\ProfileBundle\Example

services:
#    internal_profile.example:
#        class: %internal_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
