<?php

/**
 * FgApiColumnsRepository.
 */

namespace Common\UtilityBundle\Repository\Api;

use Doctrine\ORM\EntityRepository;
use Common\UtilityBundle\Entity\FgApiColumns;

/**
 * FgApiColumnsRepository.
 *
 * This class was generated by the Doctrine ORM
 * repository methods below.
 */
class FgApiColumnsRepository extends EntityRepository
{
    /**
     * Method to get field names
     *
     * @return array
     */
    public function getApiFieldNames()
    {
        $fields = $this->createQueryBuilder('f')
            ->select('f.fieldName');

        return $fields->getQuery()->getResult();
    }
}
