parameters:
#    filemanager.example.class: Common\FilemanagerBundle\Example

services:
#    filemanager.example:
#        class: %filemanager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
