<?php

namespace Common\UtilityBundle\Repository\Message;

use Doctrine\ORM\EntityRepository;
use Common\UtilityBundle\Entity\FgMessageAttachments;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * FgMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FgMessageAttachmentsRepository extends EntityRepository {

     /**
     * Method to insert the message attachments
      * 
     * @param object $messageObj
     * @param array $messageAttachmentArray (filenames after replace single quotes and appending 1,2,3 ..)
      * 
     * @return void
     */
    public function insertMessageAttachment($messageObj, $attachmentArray, $fileSizeArray) {
        
        foreach($attachmentArray as $key => $attachment)
        {
            $messageAttachmentObj = new FgMessageAttachments();
            $messageAttachmentObj->setMessageData($messageObj);
            $messageAttachmentObj->setFile($attachment);
            $messageAttachmentObj->setSize($fileSizeArray[$key]);
            $this->_em->persist($messageAttachmentObj);  
            $this->_em->flush();
        }
        return;
    }

  
     /**
     * Method to delete all attachments added to a message
      * 
     * @param int $messageId
     * 
     * @return void
     */
    public function deleteMessageAttachment($messageDataId) {
        
         $qb = $this->createQueryBuilder('ma')
                    ->delete()
                    ->where('ma.messageData=:messagedataid')
                    ->setParameter('messagedataid', $messageDataId);
        
       $result = $qb->getQuery()->execute();
       return $result;
    }
  
  
     /**
     * Method to get all attachments added to a message
      * 
     * @param int $messageId
     * 
     * @return void
     */
    public function getMessageAttachments($messageDataId) {
        
         $qb = $this->createQueryBuilder('ma')
                    ->select('ma.file,ma.size')
                    ->where('ma.messageData=:messagedataid')
                    ->setParameter('messagedataid', $messageDataId);
        
       $result = $qb->getQuery()->execute();
       return $result;
    }
  
     /**
     * Method to get all attachments added to a message
      * 
     * @param int $messageId
     * 
     * @return void
     */
    public function getMessageAttachmentsForMessage($messageId) {
        
         $qb = $this->createQueryBuilder('ma')
                    ->select('ma.file')
                    ->leftJoin('ma.messageData', 'md')
                    ->where('md.message2=:messageid')
                    ->setParameter('messageid', $messageId);
       
       $result = $qb->getQuery()->execute();
       return $result;
    }
}

