Common\UtilityBundle\Entity\FgCategorisation:
    type: entity
    table: fg_categorisation
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        categoryName:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: category_name
    lifecycleCallbacks: {  }
