Common\UtilityBundle\Entity\FgClubBookmarks:
    repositoryClass: Common\UtilityBundle\Repository\FgClubBookmarksRepository
    type: entity
    table: fg_club_bookmarks
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        type:
            type: string
            length: null
            fixed: false
            nullable: true
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
    manyToOne:
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        subfed:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                subfed_id:
                    referencedColumnName: id
            orphanRemoval: false
        filter:
            targetEntity: FgClubFilter
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                filter_id:
                    referencedColumnName: id
            orphanRemoval: false
        class:
            targetEntity: FgClubClass
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                class_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
