Common\UtilityBundle\Entity\FgClubSalutationSettingsI18n:
    type: entity
    table: fg_club_salutation_settings_i18n
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
        lang:
            id: true
            type: string
            length: 2
            fixed: true
            nullable: false
        femaleFormalLang:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: female_formal_lang
        femaleInformalLang:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: female_informal_lang
        maleFormalLang:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: male_formal_lang
        maleInformalLang:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: male_informal_lang
        familyFormalLang:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: family_formal_lang
        familyInformalLang:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: family_informal_lang
        companyNoMaincontactLang:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: company_no_maincontact_lang
        subscriberLang:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: subscriber_lang
    lifecycleCallbacks: {  }
