Common\UtilityBundle\Entity\FgClubClassificationI18n:
    type: entity
    table: fg_club_classification_i18n
    fields:
        lang:
            id: true
            type: string
            length: 2
            fixed: true
            nullable: false
        titleLang:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: title_lang
        isActive:
            type: boolean
            nullable: false
            column: is_active
    oneToOne:
        id:
            targetEntity: FgClubClassification
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
