Common\UtilityBundle\Entity\FgClubAddress:
    type: entity
    table: fg_club_address
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        company:
            type: string
            length: 255
            fixed: false
            nullable: true
        street:
            type: string
            length: 255
            fixed: false
            nullable: true
        pobox:
            type: string
            length: 255
            fixed: false
            nullable: false
        city:
            type: string
            length: 255
            fixed: false
            nullable: true
        zipcode:
            type: string
            length: 255
            fixed: false
            nullable: true
        state:
            type: string
            length: 255
            fixed: false
            nullable: true
        country:
            type: string
            length: 255
            fixed: false
            nullable: true
        language:
            type: string
            length: 255
            fixed: false
            nullable: true
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        co:
            type: string
            length: 255
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
