Common\UtilityBundle\Entity\FgClubLogNotes:
    type: entity
    table: fg_club_log_notes
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        date:
            type: datetime
            nullable: true
        type:
            type: string
            length: null
            fixed: false
            nullable: true
        valueBefore:
            type: text
            nullable: true
            column: value_before
        valueAfter:
            type: text
            nullable: true
            column: value_after
    manyToOne:
        noteClub:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                note_club_id:
                    referencedColumnName: id
            orphanRemoval: false
        noteContact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                note_contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        assignedClub:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                assigned_club_id:
                    referencedColumnName: id
            orphanRemoval: false
        changedBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                changed_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
