Common\UtilityBundle\Entity\FgClubClassification:
    repositoryClass: Common\UtilityBundle\Repository\FgClubClassificationRepository
    type: entity
    table: fg_club_classification
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        sublevelAssign:
            type: string
            length: null
            fixed: false
            nullable: true
            column: sublevel_assign
        classAssign:
            type: string
            length: null
            fixed: false
            nullable: true
            column: class_assign
        isActive:
            type: boolean
            nullable: true
            column: is_active
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
    manyToOne:
        federation:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                federation_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
