Common\UtilityBundle\Entity\FgClub:
    repositoryClass: Common\UtilityBundle\Repository\FgClubRepository
    type: entity
    table: fg_club
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        parentClubId:
            type: integer
            unsigned: false
            nullable: false
            column: parent_club_id
        federationId:
            type: integer
            unsigned: false
            nullable: true
            column: federation_id
        subFederationId:
            type: integer
            unsigned: false
            nullable: false
            column: sub_federation_id
        isFederation:
            type: boolean
            nullable: false
            column: is_federation
        isSubFederation:
            type: boolean
            nullable: false
            column: is_sub_federation
        clubType:
            type: string
            length: null
            fixed: false
            nullable: true
            column: club_type
        subfedLevel:
            type: boolean
            nullable: false
            column: subfed_level
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        urlIdentifier:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: url_identifier
        isDeleted:
            type: boolean
            nullable: false
            column: is_deleted
        defaultContactSubscription:
            type: boolean
            nullable: false
            column: default_contact_subscription
        hasSubfederation:
            type: boolean
            nullable: false
            column: has_subfederation
        settingsUpdated:
            type: datetime
            nullable: false
            column: settings_updated
        calendarColorCode:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: calendar_color_code
        assignFedmembershipWithApplication:
            type: boolean
            nullable: false
            column: assign_fedmembership_with_application
        hasNlFairgatelogo:
            type: boolean
            nullable: false
            column: has_nl_fairgatelogo
    manyToMany:
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: club
            inversedBy: null
            joinTable: null
            orderBy: null
        fedContact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: club
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }

    