Common\UtilityBundle\Entity\FgClubClass:
    type: entity
    table: fg_club_class
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        isActive:
            type: boolean
            nullable: true
            column: is_active
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
    manyToOne:
        federation:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                federation_id:
                    referencedColumnName: id
            orphanRemoval: false
        classification:
            targetEntity: FgClubClassification
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                classification_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
