Common\UtilityBundle\Entity\FgClubLanguageSettings:
    repositoryClass: Common\UtilityBundle\Repository\FgClubLanguageSettingsRepository
    type: entity
    table: fg_club_language_settings
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
        isActive:
            type: boolean
            nullable: false
            column: is_active
    manyToOne:
        clubLanguage:
            targetEntity: FgClubLanguage
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_language_id:
                    referencedColumnName: id
            orphanRemoval: false
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
