Common\UtilityBundle\Entity\FgCmsPageContentElement:
    type: entity
    repositoryClass: Common\UtilityBundle\Repository\Cms\FgCmsPageContentElementRepository    
    table: fg_cms_page_content_element
    indexes:
        page_content_type_id:
            columns:
                - page_content_type_id
        box_id:
            columns:
                - box_id
        club_id:
            columns:
                - club_id
        area_club:
            columns:
                - area_club
        form_id:
            columns:
                - form_id
        sponsor_ad_area_id:
            columns:
                - sponsor_ad_area_id
        table_id:
            columns:
                - table_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sortOrder:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: sort_order
        isDeleted:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_deleted
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        headerElementSize:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: header_element_size
        imageElementDisplayType:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: image_element_display_type
        imageElementSliderTime:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: image_element_slider_time
        imageElementClickType:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: image_element_click_type
        imageElementLinkOpentype:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: image_element_link_opentype
        mapElementLatitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: map_element_latitude
        mapElementLongitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: map_element_longitude
        mapElementShowMarker:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: map_element_show_marker
        mapElementHeight:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: map_element_height
        mapElementDisplayStyle:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: map_element_display_style
        mapElementZoomValue:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: map_element_zoom_value
        iframeElementCode:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: iframe_element_code
        iframeElementUrl:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: iframe_element_url
        iframeElementHeight:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: iframe_element_height
        isAllCategory:
            type: boolean
            nullable: true
            column: is_all_category
        isAllArea:
            type: boolean
            nullable: true
            column: is_all_area
        sharedClub:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: shared_club
        sponsorAdDisplayType:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: sponsor_ad_display_type
        sponsorAdDisplayTime:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: sponsor_ad_display_time
        sponsorAdMaxWidth:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: sponsor_ad_max_width
        twitterDefaultAccount:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: twitter_default_account
        twitterContentHeight:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: twitter_content_height
        articleDisplayType:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: listing
            column: article_display_type
        articlePerRow:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Number of articles per row for article_display_type ''listing'''
                default: '1'
            column: article_per_row
        articleCount:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Number of articles for article_display_type ''slider'''
                default: '5'
            column: article_count
        articleSliderNavigation:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: none
            column: article_slider_navigation
        articleShowThumbImg:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: article_show_thumb_img
        articleShowDate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: article_show_date
        articleShowCategory:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: article_show_category
        articleShowArea:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: article_show_area
        articleRowsCount:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Number of rows for article_display_type ''listing'''
                default: '1'
            column: article_rows_count
    manyToOne:
        pageContentType:
            targetEntity: FgCmsPageContentType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                page_content_type_id:
                    referencedColumnName: id
            orphanRemoval: false
        box:
            targetEntity: FgCmsPageContainerBox
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                box_id:
                    referencedColumnName: id
            orphanRemoval: false
        club:
            targetEntity: FgClub
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        areaClub:
            targetEntity: FgClub
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                area_club:
                    referencedColumnName: id
            orphanRemoval: false
        sponsorAdArea:
            targetEntity: FgSmAdArea
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sponsor_ad_area_id:
                    referencedColumnName: id
            orphanRemoval: false
        form:
            targetEntity: FgCmsForms
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                form_id:
                    referencedColumnName: id
            orphanRemoval: false
        table:
            targetEntity: FgCmsContactTable
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                table_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
