Common\UtilityBundle\Entity\FgCmsPageContainer:
    repositoryClass: Common\UtilityBundle\Repository\Cms\FgCmsPageContainerRepository
    type: entity
    table: fg_cms_page_container
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
    manyToOne:
        page:
            targetEntity: FgCmsPage
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                page_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
