Common\UtilityBundle\Entity\FgCmsPageArticleCategories:
    repositoryClass: Common\UtilityBundle\Repository\Cms\FgCmsPageArticleCategoriesRepository
    type: entity
    table: fg_cms_page_article_categories
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        page:
            targetEntity: FgCmsPage
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                page_id:
                    referencedColumnName: id
            orphanRemoval: false
        category:
            targetEntity: FgCmsArticleCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
