Common\UtilityBundle\Entity\FgCmsPageContainerBox:
    repositoryClass: Common\UtilityBundle\Repository\Cms\FgCmsPageContainerBoxRepository
    type: entity
    table: fg_cms_page_container_box
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
    manyToOne:
        column:
            targetEntity: FgCmsPageContainerColumn
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                column_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
