Common\UtilityBundle\Entity\FgCmsPageContentElementFormFieldOptionsI18n:
    repositoryClass: Common\UtilityBundle\Repository\Cms\FgCmsPageContentElementFormFieldOptionsI18nRepository
    type: entity
    table: fg_cms_page_content_element_form_field_options_i18n
    fields:
        lang:
            id: true
            type: string
            length: 2
            fixed: true
            nullable: false
        selectionValueNameLang:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: selection_value_name_lang
    oneToOne:
        id:
            targetEntity: FgCmsPageContentElementFormFieldOptions
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
