Common\UtilityBundle\Entity\FgCmChangeToconfirm:
    repositoryClass: Common\UtilityBundle\Repository\FgCmChangeToconfirmRepository
    type: entity
    table: fg_cm_change_toconfirm
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        roleId:
            type: integer
            unsigned: false
            nullable: true
            column: role_id
        date:
            type: datetime
            nullable: true
        value:
            type: text
            nullable: true
        logOnce:
            type: boolean
            nullable: true
            column: log_once
        type:
            type: string
            length: null
            fixed: false
            nullable: false
        confirmStatus:
            type: string
            length: null
            fixed: false
            nullable: true
            column: confirm_status
    manyToOne:
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        attribute:
            targetEntity: FgCmAttribute
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                attribute_id:
                    referencedColumnName: id
            orphanRemoval: false
            nullable: true
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        changedBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                changed_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
