Common\UtilityBundle\Entity\FgCmsArticleMedia:
    repositoryClass: Common\UtilityBundle\Repository\Article\FgCmsArticleMediaRepository
    type: entity
    table: fg_cms_article_media
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
    manyToOne:
        article:
            targetEntity: FgCmsArticle
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                article_id:
                    referencedColumnName: id
            orphanRemoval: false
        items:
            targetEntity: FgGmItems
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                items_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
