Common\UtilityBundle\Entity\FgCmContactPrivacy:
    repositoryClass: Common\UtilityBundle\Repository\FgCmContactPrivacyRepository
    type: entity
    table: fg_cm_contact_privacy
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        privacy:
            type: string
            length: null
            fixed: false
            nullable: false
    manyToOne:
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        attribute:
            targetEntity: FgCmAttribute
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                attribute_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
