Common\UtilityBundle\Entity\FgCmsPageContentElementMembershipSelections:
    repositoryClass: Common\UtilityBundle\Repository\Cms\FgCmsPageContentElementMembershipSelectionsRepository
    type: entity
    table: fg_cms_page_content_element_membership_selections
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        field:
            targetEntity: FgCmsPageContentElementFormFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                field_id:
                    referencedColumnName: id
            orphanRemoval: false
        membership:
            targetEntity: FgCmMembership
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                membership_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
