Common\UtilityBundle\Entity\FgCmsNavigation:
    repositoryClass: Common\UtilityBundle\Repository\Cms\FgCmsNavigationRepository
    type: entity
    table: fg_cms_navigation
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        isActive:
            type: boolean
            nullable: true
            column: is_active
        sortOrder:
            type: integer
            unsigned: false
            nullable: true
            column: sort_order
        isPublic:
            type: boolean
            nullable: true
            column: is_public
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        editedAt:
            type: datetime
            nullable: true
            column: edited_at
        type:
            type: string
            length: null
            fixed: false
            nullable: true
        externalLink:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: external_link
        navigationUrl:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: navigation_url
        isAdditional:
            type: boolean
            nullable: false
            column: is_additional
    manyToOne:
        parent:
            targetEntity: FgCmsNavigation
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent_id:
                    referencedColumnName: id
            orphanRemoval: false
        page:
            targetEntity: FgCmsPage
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                page_id:
                    referencedColumnName: id
            orphanRemoval: false
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        editedBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                edited_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
