Common\UtilityBundle\Entity\FgCmsContactTableFilter:
    repositoryClass: Common\UtilityBundle\Repository\Cms\FgCmsContactTableFilterRepository
    type: entity
    table: fg_cms_contact_table_filter
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        filterType:
            type: string
            length: null
            fixed: false
            nullable: false
            column: filter_type
        title:
            type: string
            length: 255
            fixed: false
            nullable: false
        filterSubtypeIds:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: filter_subtype_ids
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
        isDeleted:
            type: boolean
            nullable: false
            column: is_deleted
    manyToOne:
        table:
            targetEntity: FgCmsContactTable
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                table_id:
                    referencedColumnName: id
            orphanRemoval: false
        attribute:
            targetEntity: FgCmAttribute
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                attribute_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
