Common\UtilityBundle\Entity\FgCmMembershipHistory:
    repositoryClass: Common\UtilityBundle\Repository\FgCmMembershipHistoryRepository
    type: entity
    table: fg_cm_membership_history
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        membershipType:
            type: string
            length: null
            fixed: false
            nullable: true
            column: membership_type
        joiningDate:
            type: datetime
            nullable: true
            column: joining_date
        leavingDate:
            type: datetime
            nullable: true
            column: leaving_date
    manyToOne:
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        membership:
            targetEntity: FgCmMembership
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                membership_id:
                    referencedColumnName: id
            orphanRemoval: false
        membershipClub:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                membership_club_id:
                    referencedColumnName: id
            orphanRemoval: false
        changedBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                changed_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
