Common\UtilityBundle\Entity\FgCmMembershipLog:
    repositoryClass: Common\UtilityBundle\Repository\FgCmMembershipLogRepository
    type: entity
    table: fg_cm_membership_log
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        date:
            type: datetime
            nullable: true
        kind:
            type: string
            length: null
            fixed: false
            nullable: true
        field:
            type: string
            length: 255
            fixed: false
            nullable: true
        valueBefore:
            type: text
            nullable: true
            column: value_before
        valueAfter:
            type: text
            nullable: true
            column: value_after
    manyToOne:
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        membership:
            targetEntity: FgCmMembership
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                membership_id:
                    referencedColumnName: id
            orphanRemoval: false
        changedBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                changed_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
