Common\UtilityBundle\Entity\FgCmFedmembershipConfirmationLog:
    repositoryClass: Common\UtilityBundle\Repository\FgCmFedmembershipConfirmationLogRepository
    type: entity
    table: fg_cm_fedmembership_confirmation_log
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        existingClubIds:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: existing_club_ids
        modifiedDate:
            type: datetime
            nullable: true
            column: modified_date
        decidedDate:
            type: datetime
            nullable: true
            column: decided_date
        status:
            type: string
            length: null
            fixed: false
            nullable: false
        isMerging:
            type: integer
            unsigned: false
            nullable: false
            column: is_merging
    manyToOne:
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        federationClub:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                federation_club_id:
                    referencedColumnName: id
            orphanRemoval: false
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        modifiedBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                modified_by:
                    referencedColumnName: id
            orphanRemoval: false
        decidedBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                decided_by:
                    referencedColumnName: id
            orphanRemoval: false
        fedmembershipValueBefore:
            targetEntity: FgCmMembership
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fedmembership_value_before:
                    referencedColumnName: id
            orphanRemoval: false
        fedmembershipValueAfter:
            targetEntity: FgCmMembership
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fedmembership_value_after:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
