Common\UtilityBundle\Entity\FgCmsPageContentMedia:
    repositoryClass: Common\UtilityBundle\Repository\Cms\FgCmsPageContentMediaRepository
    type: entity
    table: fg_cms_page_content_media
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
        imageElementLinkType:
            type: string
            length: null
            fixed: false
            nullable: true
            column: image_element_link_type
        imageElementExternalLink:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: image_element_external_link
    manyToOne:
        item:
            targetEntity: FgGmItems
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                item_id:
                    referencedColumnName: id
            orphanRemoval: false
        textElement:
            targetEntity: FgCmsPageContentTextElement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                text_element_id:
                    referencedColumnName: id
            orphanRemoval: false
        element:
            targetEntity: FgCmsPageContentElement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                element_id:
                    referencedColumnName: id
            orphanRemoval: false
        navigation:
            targetEntity: FgCmsNavigation
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                navigation_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
