Common\UtilityBundle\Entity\FgCnSmsClubPackages:
    type: entity
    table: fg_cn_sms_club_packages
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        sortOrder:
            type: integer
            unsigned: false
            nullable: true
            column: sort_order
        price:
            type: decimal
            nullable: true
        totalCredits:
            type: integer
            unsigned: false
            nullable: true
            column: total_credits
        balanceCredits:
            type: integer
            unsigned: false
            nullable: true
            column: balance_credits
        sponsorType:
            type: string
            length: null
            fixed: false
            nullable: true
            column: sponsor_type
        sponsorText:
            type: text
            nullable: true
            column: sponsor_text
        clubId:
            type: integer
            unsigned: false
            nullable: false
            column: club_id
        bookingDate:
            type: datetime
            nullable: true
            column: booking_date
        isClub:
            type: boolean
            nullable: false
            column: is_club
        isAll:
            type: integer
            unsigned: false
            nullable: false
            column: is_all
    lifecycleCallbacks: {  }
