Common\UtilityBundle\Entity\FgCnSmsContacts:
    type: entity
    table: fg_cn_sms_contacts
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        smsId:
            type: integer
            unsigned: false
            nullable: false
            column: sms_id
        filterId:
            type: integer
            unsigned: false
            nullable: true
            column: filter_id
        categoryId:
            type: integer
            unsigned: false
            nullable: true
            column: category_id
        roleId:
            type: integer
            unsigned: false
            nullable: true
            column: role_id
        functionId:
            type: integer
            unsigned: false
            nullable: true
            column: function_id
        selectionType:
            type: string
            length: null
            fixed: false
            nullable: false
            column: selection_type
    lifecycleCallbacks: {  }
