Common\UtilityBundle\Entity\FgCnNewsletterSidebar:    
    repositoryClass: Common\UtilityBundle\Repository\FgCnNewsletterSidebarRepository
    type: entity
    table: fg_cn_newsletter_sidebar
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 160
            fixed: false
            nullable: true
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
    manyToOne:
        sponsorAdArea:
            targetEntity: FgSmAdArea
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sponsor_ad_area_id:
                    referencedColumnName: id
            orphanRemoval: false
        newsletter:
            targetEntity: FgCnNewsletter
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                newsletter_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
