Common\UtilityBundle\Entity\FgCnNewsletterArticleDocuments:
    repositoryClass: Common\UtilityBundle\Repository\FgCnNewsletterArticleDocumentsRepository
    type: entity
    table: fg_cn_newsletter_article_documents
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
        docType:
            type: string
            length: null
            fixed: false
            nullable: true
            column: doc_type
        filename:
            type: string
            length: 255
            fixed: false
            nullable: true
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        fileManager:
            targetEntity: FgFileManager
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                file_manager_id:
                    referencedColumnName: id
            orphanRemoval: false
        documents:
            targetEntity: FgDmDocuments
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                documents_id:
                    referencedColumnName: id
            orphanRemoval: false
        newsletter:
            targetEntity: FgCnNewsletter
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                newsletter_id:
                    referencedColumnName: id
            orphanRemoval: false
        article:
            targetEntity: FgCnNewsletterArticle
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                article_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
