Common\UtilityBundle\Entity\FgCnRecepients:
    repositoryClass: Common\UtilityBundle\Repository\FgCnRecepientsRepository
    type: entity
    table: fg_cn_recepients
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: true
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        filterData:
            type: text
            nullable: false
            column: filter_data
        isAllActive:
            type: boolean
            nullable: false
            column: is_all_active
        contactCount:
            type: integer
            unsigned: false
            nullable: false
            column: contact_count
        mandatoryCount:
            type: integer
            unsigned: false
            nullable: false
            column: mandatory_count
        subscriberCount:
            type: integer
            unsigned: false
            nullable: false
            column: subscriber_count
        tempId:
            type: string
            length: 15
            fixed: false
            nullable: false
            column: temp_id
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
    manyToOne:
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
