Common\UtilityBundle\Entity\FgCnSmsTeamPackages:
    type: entity
    table: fg_cn_sms_team_packages
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        clubPackagesId:
            type: integer
            unsigned: false
            nullable: false
            column: club_packages_id
        teamId:
            type: integer
            unsigned: false
            nullable: false
            column: team_id
    lifecycleCallbacks: {  }
