Common\UtilityBundle\Entity\FgCnSmsLang:
    type: entity
    table: fg_cn_sms_lang
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        smsId:
            type: integer
            unsigned: false
            nullable: false
            column: sms_id
        languageCode:
            type: string
            length: 2
            fixed: false
            nullable: true
            column: language_code
    lifecycleCallbacks: {  }
