Common\UtilityBundle\Entity\FgCnSmsPackages:
    type: entity
    table: fg_cn_sms_packages
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        credits:
            type: integer
            unsigned: false
            nullable: true
        price:
            type: decimal
            nullable: true
        visibility:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
