Common\UtilityBundle\Entity\FgDmAssigmentExclude:
    type: entity
    table: fg_dm_assigment_exclude
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        document:
            targetEntity: FgDmDocuments
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                document_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
