Common\UtilityBundle\Entity\FgDmDocuments:
    repositoryClass: Common\UtilityBundle\Repository\FgDmDocumentsRepository
    type: entity
    table: fg_dm_documents
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 160
            fixed: false
            nullable: true
        description:
            type: text
            nullable: true
        author:
            type: string
            length: 160
            fixed: false
            nullable: true
        filter:
            type: text
            nullable: true
        documentType:
            type: string
            length: null
            fixed: false
            nullable: false
            column: document_type
        depositedWith:
            type: string
            length: null
            fixed: false
            nullable: false
            column: deposited_with
        visibleFor:
            type: string
            length: null
            fixed: false
            nullable: true
            column: visible_for
        isVisibleToContact:
            type: integer
            unsigned: false
            nullable: true
            column: is_visible_to_contact
        functionSel:
            type: string
            length: null
            fixed: false
            nullable: true
            column: function_sel
        isPublishLink:
            type: integer
            unsigned: false
            nullable: false
            column: is_publish_link
    manyToOne:
        subcategory:
            targetEntity: FgDmDocumentSubcategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                subcategory_id:
                    referencedColumnName: id
            orphanRemoval: false
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        currentRevision:
            targetEntity: FgDmVersion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                current_revision:
                    referencedColumnName: id
            orphanRemoval: false
        category:
            targetEntity: FgDmDocumentCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
