Common\UtilityBundle\Entity\FgDmDocumentSubcategoryI18n:
    repositoryClass: Common\UtilityBundle\Repository\FgDmDocumentSubcategoryI18nRepository
    type: entity
    table: fg_dm_document_subcategory_i18n
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
        lang:
            id: true
            type: string
            length: 2
            fixed: true
            nullable: false
        titleLang:
            type: string
            length: 160
            fixed: false
            nullable: true
            column: title_lang
    lifecycleCallbacks: {  }
