Common\UtilityBundle\Entity\FgDmDocumentCategory:
    repositoryClass: Common\UtilityBundle\Repository\FgDmDocumentCategoryRepository
    type: entity
    table: fg_dm_document_category
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        documentType:
            type: string
            length: null
            fixed: false
            nullable: true
            column: document_type
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
    manyToOne:
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
