Common\UtilityBundle\Entity\FgDnClubDomains:
    repositoryClass: Common\UtilityBundle\Repository\FgDnClubDomainsRepository
    type: entity
    table: fg_dn_club_domains
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        domain:
            type: string
            length: 256
            fixed: false
            nullable: true
        isDefault:
            type: boolean
            nullable: false
            column: is_default
        domainType:
            type: string
            length: null
            fixed: false
            nullable: true
            column: domain_type
        mailRequestStatus:
            type: string
            length: null
            fixed: false
            nullable: false
            column: mail_request_status
        isSecure:
            type: boolean
            nullable: false
            column: is_secure
    manyToOne:
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        mailRequester:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                mail_requester_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
