Common\UtilityBundle\Entity\FgEmCalendarRules:
    type: entity
    table: fg_em_calendar_rules
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        freq:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: FREQ
        byday:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: BYDAY
        interval:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: INTERVAL
        bymonthday:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: BYMONTHDAY
        bymonth:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: BYMONTH
    lifecycleCallbacks: {  }
