Common\UtilityBundle\Entity\FgForumTopicData:
    repositoryClass: Common\UtilityBundle\Repository\Forum\FgForumTopicDataRepository
    type: entity
    table: fg_forum_topic_data
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        postContent:
            type: text
            nullable: false
            column: post_content
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        uniquePostId:
            type: integer
            unsigned: false
            nullable: false
            column: unique_post_id
    manyToOne:
        updatedBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        forumTopic:
            targetEntity: FgForumTopic
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                forum_topic_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
