Common\UtilityBundle\Entity\FgForumFollowers:
    repositoryClass: Common\UtilityBundle\Repository\Forum\FgForumFollowersRepository
    type: entity
    table: fg_forum_followers
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        isFollowForum:
            type: boolean
            nullable: true
            column: is_follow_forum
    manyToOne:
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        group:
            targetEntity: FgRmRole
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                group_id:
                    referencedColumnName: id
            orphanRemoval: false
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
