Common\UtilityBundle\Entity\FgGmItemI18n:
    repositoryClass: Common\UtilityBundle\Repository\Gallery\FgGmItemI18nRepository
    type: entity
    table: fg_gm_item_i18n
    fields:
        lang:
            id: true
            type: string
            length: 2
            fixed: true
            nullable: false
        descriptionLang:
            type: string
            length: 145
            fixed: false
            nullable: true
            column: description_lang
        isActive:
            type: boolean
            nullable: true
            column: is_active
    oneToOne:
        id:
            targetEntity: FgGmItems
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
