Common\UtilityBundle\Entity\FgNotificationSpool:
    repositoryClass: Common\UtilityBundle\Repository\FgNotificationSpoolRepository
    type: entity
    table: fg_notification_spool
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        notificationType:
            type: string
            length: null
            fixed: false
            nullable: true
            column: notification_type
        email:
            type: string
            length: 250
            fixed: false
            nullable: true
        templateContent:
            type: blob
            nullable: true
            column: template_content
    lifecycleCallbacks: {  }
