Common\UtilityBundle\Entity\FgRmFunctionI18n:
    type: entity
    table: fg_rm_function_i18n
    fields:
        lang:
            id: true
            type: string
            length: 2
            fixed: true
            nullable: false
        titleLang:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: title_lang
        isActive:
            type: boolean
            nullable: false
            column: is_active
    oneToOne:
        id:
            targetEntity: FgRmFunction
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
