Common\UtilityBundle\Entity\FgRmRoleContact:
    repositoryClass: Common\UtilityBundle\Repository\FgRmRoleContactRepository
    type: entity
    table: fg_rm_role_contact
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        updateType:
            type: string
            length: null
            fixed: false
            nullable: true
            column: update_type
        updateCount:
            type: integer
            unsigned: false
            nullable: false
            column: update_count
        updateTime:
            type: datetime
            nullable: true
            column: update_time
        isRemoved:
            type: boolean
            nullable: false
            column: is_removed
    manyToOne:
        fgRmCrf:
            targetEntity: FgRmCategoryRoleFunction
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fg_rm_crf_id:
                    referencedColumnName: id
            orphanRemoval: false
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        assinedClub:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                assined_club_id:
                    referencedColumnName: id
            orphanRemoval: false
        contactClub:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_club_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
