Common\UtilityBundle\Entity\FgRmRole:
    repositoryClass: Common\UtilityBundle\Repository\FgRmRoleRepository
    type: entity
    table: fg_rm_role
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        isActive:
            type: boolean
            nullable: true
            column: is_active
        isExecutiveBoard:
            type: boolean
            nullable: true
            column: is_executive_board
        sortOrder:
            type: integer
            unsigned: false
            nullable: false
            column: sort_order
        description:
            type: text
            nullable: true
        image:
            type: string
            length: 255
            fixed: false
            nullable: true
        type:
            type: string
            length: null
            fixed: false
            nullable: false
        filterUpdated:
            type: datetime
            nullable: true
            column: filter_updated
        isDeactivatedForum:
            type: boolean
            nullable: true
            column: is_deactivated_forum
        calendarColorCode:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: calendar_color_code
        visibleForAll:
            type: boolean
            nullable: false
            column: visible_for_all
    manyToOne:
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        teamCategory:
            targetEntity: FgTeamCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                team_category_id:
                    referencedColumnName: id
            orphanRemoval: false
        filter:
            targetEntity: FgFilter
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                filter_id:
                    referencedColumnName: id
            orphanRemoval: false
        category:
            targetEntity: FgRmCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
