Common\UtilityBundle\Entity\FgRmRoleLog:
    repositoryClass: Common\UtilityBundle\Repository\FgRmRoleLogRepository
    type: entity
    table: fg_rm_role_log
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        clubId:
            type: integer
            unsigned: false
            nullable: false
            column: club_id
        date:
            type: datetime
            nullable: true
        kind:
            type: string
            length: null
            fixed: false
            nullable: true
        field:
            type: string
            length: 255
            fixed: false
            nullable: true
        valueBefore:
            type: text
            nullable: true
            column: value_before
        valueAfter:
            type: text
            nullable: true
            column: value_after
        historicalId:
            type: integer
            unsigned: false
            nullable: true
            column: historical_id
        isHistorical:
            type: boolean
            nullable: false
            column: is_historical
        bookingId:
            type: integer
            unsigned: false
            nullable: true
            column: booking_id
        importTable:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: import_table
        importContact:
            type: integer
            unsigned: false
            nullable: false
            column: import_contact
    manyToOne:
        role:
            targetEntity: FgRmRole
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
            orphanRemoval: false
        changedBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                changed_by:
                    referencedColumnName: id
            orphanRemoval: false
        contactlog:
            targetEntity: FgCmChangeLog
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contactlog_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
