Common\UtilityBundle\Entity\FgSmSponsorLog:
    repositoryClass: Common\UtilityBundle\Repository\FgSmSponsorLogRepository    
    type: entity
    table: fg_sm_sponsor_log
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        date:
            type: datetime
            nullable: true
        kind:
            type: string
            length: null
            fixed: false
            nullable: true
        actionType:
            type: string
            length: null
            fixed: false
            nullable: true
            column: action_type
    manyToOne:
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
        changedBy:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                changed_by:
                    referencedColumnName: id
            orphanRemoval: false
        category:
            targetEntity: FgSmCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
        service:
            targetEntity: FgSmServices
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                service_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
