Common\UtilityBundle\Entity\FgSmPaymentplans:
    repositoryClass: Common\UtilityBundle\Repository\FgSmPaymentplansRepository
    type: entity
    table: fg_sm_paymentplans
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        date:
            type: datetime
            nullable: false
        amount:
            type: decimal
            nullable: true
        discountType:
            type: string
            length: null
            fixed: false
            nullable: true
            column: discount_type
        discount:
            type: decimal
            nullable: true
    manyToOne:
        booking:
            targetEntity: FgSmBookings
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                booking_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
