Common\UtilityBundle\Entity\FgTableSettings:
    repositoryClass: Common\UtilityBundle\Repository\FgTableSettingsRepository
    type: entity
    table: fg_table_settings
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        attributes:
            type: text
            nullable: true
        isTemp:
            type: boolean
            nullable: false
            column: is_temp
        type:
            type: string
            length: null
            fixed: false
            nullable: false
    manyToOne:
        contact:
            targetEntity: FgCmContact
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
        club:
            targetEntity: FgClub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
