Common\UtilityBundle\Entity\FgTmTheme:
    repositoryClass: Common\UtilityBundle\Repository\Cms\FgTmThemeRepository 
    type: entity
    table: fg_tm_theme
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
            fixed: false
            nullable: true
        sortOrder:
            type: integer
            unsigned: false
            nullable: true
            column: sort_order
        themeOptions:
            type: text
            nullable: false
            column: theme_options
        isActive:
            type: boolean
            nullable: false
            column: is_active
    lifecycleCallbacks: {  }
