Common\UtilityBundle\Entity\SfGuardGroup:
    repositoryClass: Common\UtilityBundle\Repository\SfGuardGroupRepository
    type: entity
    table: sf_guard_group
    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: IDENTITY
 
    