Common\UtilityBundle\Entity\SfGuardUserTeam:
    repositoryClass: Common\UtilityBundle\Repository\SfGuardUserTeamRepository
    type: entity
    table: sf_guard_user_team
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        role:
            targetEntity: FgRmRole
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: SfGuardUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        group:
            targetEntity: SfGuardGroup
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                group_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
