admin_utility_homepage:
    path:     /register
    defaults: { _controller: AdminUtilityBundle:Register:index }
   
admin_confirmation:
    path:     /{urlIdentifier}/confirmClub/{clubId}/{token}
    defaults: { _controller: AdminUtilityBundle:Register:confirmMail } 
    
